# ===========================================
# Deployment
# ===========================================
apiVersion: v1
kind: Service
metadata:
  name: job-services-service
spec:
  ports:
    - port: 8080
  selector:
    app: job-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-services
spec:
  selector:
    matchLabels:
      app: job-services
  template:
    metadata:
      labels:
        app: job-services
    spec:
      containers:
        - name: job-services
          image: registry.savioresende.com/job-services:DEPLOYMENT_VERSION
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: myregistrykey # this is at the k8s environment

